# Generated by Django 5.2.6 on 2025-09-22 14:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv_uploads/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed', models.BooleanField(default=False)),
                ('total_urls', models.IntegerField(default=0)),
                ('processed_urls', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True)),
                ('meta_description', models.TextField(blank=True)),
                ('status_code', models.IntegerField(null=True)),
                ('scraping_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('processing', 'Processing')], default='pending', max_length=20)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('structured_data', models.JSONField(blank=True, default=dict)),
                ('vectorized', models.BooleanField(default=False)),
                ('vector_id', models.CharField(blank=True, max_length=100)),
                ('csv_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_urls', to='knowledge_base.csvupload')),
            ],
            options={
                'unique_together': {('csv_upload', 'url')},
            },
        ),
    ]
